version: "2"
services:
  mysql:
    image: 'mysql:5.6.35'
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: docker
  php: 
    build: docker/dockerfiles/php/
    links:
      - mysql:mysqldb
    volumes: 
      - ./:/var/www/html
  apache: 
    build: docker/dockerfiles/apache/ 
    links: 
      - php:phpfpm 
    volumes: 
      - ./:/var/www/html
    ports:
      - 9000:80